# -*- coding: utf-8 -*-
"""
>>> from samila import *
>>> import os
>>> g = GenerativeImage(data="data.json")
Traceback (most recent call last):
        ...
samila.errors.samilaDataError: Provided data file is not supported. It should be either file or io.IOBase.
>>> with open('data.json', 'r')
"""
